AI ML ASSIGNMENT 1

Task - 1 Create a pandas dataframe (DataFrame name as 'df') with numpy random values (4 features and 4 observation)

In [1]:
import pandas as pd
import numpy as np
data=np.random.rand(4,4)
dframe=pd.DataFrame(data,columns=['I','II','III','IV'])
print(dframe)

          I        II       III        IV
0  0.171077  0.210947  0.291061  0.051772
1  0.069043  0.201671  0.870053  0.399265
2  0.328311  0.371488  0.729623  0.452755
3  0.628736  0.173450  0.158015  0.820459

Task - 2 Rename the task - 1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [ ]:
dframe.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
print(dframe)

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.279744        0.193180        0.053096        0.493901
1        0.380089        0.783105        0.063182        0.789761
2        0.030812        0.719827        0.143832        0.989834
3        0.609279        0.976632        0.810760        0.793367

Task - 3 Find the descriptive statistics of the 'df' dataframe.

In [ ]:
dframe.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.324981        0.668186        0.267717        0.766716
std          0.239753        0.334984        0.364298        0.204492
min          0.030812        0.193180        0.053096        0.493901
25%          0.217511        0.588165        0.060660        0.715796
50%          0.329917        0.751466        0.103507        0.791564
75%          0.437387        0.831487        0.310564        0.842484
max          0.609279        0.976632        0.810760        0.989834

Task - 4 Check for the null values in 'df' and find the data type of the columns

In [ ]:
dframe.isnull().sum() #null value check
dframe.dtypes #data types

Random value 1    float64
Random value 2    float64
Random value 3    float64
Random value 4    float64
dtype: object

Task - 5 Display the 'Random value 2' & 'Random value 3' columns with location method and index location method

In [ ]:
dframe[['Random value 2', 'Random value 3']] #using location method
dframe.iloc[:, 1:3] #using index location

   Random value 2  Random value 3
0        0.193180        0.053096
1        0.783105        0.063182
2        0.719827        0.143832
3        0.976632        0.810760